### Generating some vectors

In [8]:
from pylab import *
from numpy import *

v1 = arange(1, 10, 1)

# Linspace

v2 = linspace(0, 5, 39)
print v1

print "Hej Mattias!"



[1 2 3 4 5 6 7 8 9]
Hej Mattias!


In [11]:
a = array([-1, 0, 2])
b = 3 * a
c = a + 2

print a, b, c

[-1  0  2] [-3  0  6] [1 2 4]


In [19]:
a = array([2.0, 3.0, 4.0])
b = array([-1.0, 1.0, 2.0])

c = a + b
d = a * b
e = a / b
f = b**2
print "a + b: ", c
print "a * b: " , d
print "a / b: " , e
print "b**2:  " , f

a + b:  [ 1.  4.  6.]
a * b:  [-2.  3.  8.]
a / b:  [-2.  3.  2.]
b**2:   [ 1.  1.  4.]


### Scalar and vector product

In [23]:
ip = dot(a, b)
print ip

v_length = norm(a)
print v_length

cross_product = cross(a, b)
print cross_product



9.0
5.38516480713
[ 2. -8.  5.]


##### SCALAR PRODUCT

$$\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^n a_i b_i = a_1 b_1 + a_2 b_2 + \dots + a_n b_n$$

https://en.wikipedia.org/wiki/File:Right_hand_rule_cross_product.svg

https://en.wikipedia.org/wiki/File:Sarrus_rule_cross_product.svg

In [25]:
e = a / norm(e)

tproj = dot(b, e) * e
print tproj

[ 10.55172414  15.82758621  21.10344828]


In [26]:
y = [1, 3, 5, 99, 81]
print sqrt(y)

[ 1.          1.73205081  2.23606798  9.94987437  9.        ]


In [41]:
from pylab import * # Vi importerar allt fran pylab-modulen >>> X = linspace(-pi, pi, 300

X = linspace(-pi, pi, 300)
C, S = cos(X), sin(X)
plot(X, C, color="blue", linewidth=2.5, linestyle="-", label="cosinus")
plot(X, S, color="red", linewidth=2.5, linestyle="-", label="sinus")
legend(loc="upper left")
axis
xlabel("x")
ylabel("y")
title("Sinus")
show()

## Uppgift 1

In [84]:
def f(x):
    return cos(x)

#print "f-test 1: ", f(pi/3)

def p2(x):
    return 1 - (x**2)/2

#print "p2(2) should equal -1 : ", p2(2)
#print "p2(1) should equal 0.5 : ", p2(1.0)



def p4(x):
    return p2(x) + (x**4)/24

#print "p4test 1: ", p4(1.0)
#print "p4test 1: ", p4(2.0)

#FUNKAR FINT above this line

def p6(x):
    return p4(x) - (x**6)/720

print p6(2.0)

# REGRESSION TESTING COMPLETED


# Intervall:  −2π ≤ x ≤ 2π.

-0.422222222222
